services:
  - type: web
    name: typebot-web
    env: docker
    plan: starter
    autoDeploy: true
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: typebot-web
          property: url
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: ENCRYPTION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: typebot-db
          property: connectionString

databases:
  - name: typebot-db
    databaseName: typebot_db
    user: typebot_user
